class ModelUf {
  static final Map<String, dynamic> Ufs = {
    "AC": {"nome": "Acre", "codigo_ibge": 12},
    "AL": {"nome": "Alagoas", "codigo_ibge": 27},
    "AP": {"nome": "Amapá", "codigo_ibge": 16},
    "AM": {"nome": "Amazonas", "codigo_ibge": 13},
    "BA": {"nome": "Bahia", "codigo_ibge": 29},
    "CE": {"nome": "Ceará", "codigo_ibge": 23},
    "DF": {"nome": "Distrito Federal", "codigo_ibge": 53},
    "ES": {"nome": "Espírito Santo", "codigo_ibge": 32},
    "GO": {"nome": "Goiás", "codigo_ibge": 52},
    "MA": {"nome": "Maranhão", "codigo_ibge": 21},
    "MT": {"nome": "Mato Grosso", "codigo_ibge": 51},
    "MS": {"nome": "Mato Grosso do Sul", "codigo_ibge": 50},
    "MG": {"nome": "Minas Gerais", "codigo_ibge": 31},
    "PA": {"nome": "Pará", "codigo_ibge": 15},
    "PB": {"nome": "Paraíba", "codigo_ibge": 25},
    "PR": {"nome": "Paraná", "codigo_ibge": 41},
    "PE": {"nome": "Pernambuco", "codigo_ibge": 26},
    "PI": {"nome": "Piauí", "codigo_ibge": 22},
    "RJ": {"nome": "Rio de Janeiro", "codigo_ibge": 33},
    "RN": {"nome": "Rio Grande do Norte", "codigo_ibge": 24},
    "RS": {"nome": "Rio Grande do Sul", "codigo_ibge": 43},
    "RO": {"nome": "Rondônia", "codigo_ibge": 11},
    "RR": {"nome": "Roraima", "codigo_ibge": 14},
    "SC": {"nome": "Santa Catarina", "codigo_ibge": 42},
    "SP": {"nome": "São Paulo", "codigo_ibge": 35},
    "SE": {"nome": "Sergipe", "codigo_ibge": 28},
    "TO": {"nome": "Tocantins", "codigo_ibge": 17},
  };
}
